### ISSUE TITLE
admin password not working

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/SocialPrescribingWiki#4]
https://develop-official.hlpwiki.agileventures.org/index.php/Main_Page

**Comment by mattwr18** [comment]
Similarly, this can be closed as we now have access to sign in as an Admin @tansaku

**Comment by tansaku** [comment]
great work @mattwr18 ! what was the fix?

**Comment by mattwr18** [comment]
yes, good to have a copy of the fix in case others run into the same issue later in life... One thing to note as well is that the `changePassword.php` script requires a password of at least 10 characters. Not sure what happens if you try with less as I read that before trying. 

Also, this needs to be placed in the same block as the creation of the LocalSettings to have access to `$MEDIAWIKI_ADMIN_PASS`, if memory serves me.
