### ISSUE TITLE
want to get VisualEditor (which needs parsoid) working

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/SocialPrescribingWiki#5]
https://www.mediawiki.org/wiki/Extension:VisualEditor

https://www.mediawiki.org/wiki/Parsoid

**Comment by tansaku** [comment]
From Parsoid troubleshooting

* https://develop-official.hlpwiki.agileventures.org/api.php works (this is api we will use)

**Comment by mattwr18** [comment]
We got were able to get parsoid successfully installed with `npm install -g parsoid --unsafe-perm`, we still weren't able to run the command `node bin/server.js` because it wasn't clear where the parsoid directory was, so we installed used `npm install parsoid` which created a `node_modules` directory and were able to run `node bin/server.js` from within it, which gave this: https://gist.github.com/mattwr18/fc6322ff931fafd9f01be0b6ef3aad9d#file-output_of_node_bin_server-js
Complaining about not finding modules

I've added some steps to `RUN cd /etc` and `RUN npm install parsoid` because it seems like that is where the logic lives. at least the `config.yaml`  and `settings.js`; however, this caused these errors when building the Dockerfile
```
npm WARN saveError ENOENT: no such file or directory, open '/var/www/html/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/var/www/html/package.json'
npm WARN html No description
npm WARN html No repository field.
npm WARN html No README data
npm WARN html No license field.
```
I decided to go back to the Parsoid Setup instructions:
https://www.mediawiki.org/wiki/Parsoid/Setup
and I walked through the instructions again and was able to get `parsoid` installed through `apt-get` using `--allow-unauthenticated`

I added a `service parsoid start` to the end of the `entrypoint.sh` to start parsoid up and pushed it to dokku, which didn't make any noticeable changes, but the log output seems to have started the parsoid server 
```
2018-10-24T17:58:28.738727357Z app[web.1]: Started Parsoid server on port 8142
```
I thought there could be some issue with the `CMD ["apachectl", "-e", "info", "-D", "FOREGROUND"]` overwriting it and wanted to test if I could start the apache2 server in the same way, and be able to visit the site. So I commented out the line from the Dockerfile and added the command to the `entrypoint.sh` and pushed it up, which didn't make any differences. 

I could still visit the site and login, but clicking on `edit` doesn't open the visual editor, so there is still something that isn't quite right with the setup. 

This gave the output above about parsoid, but also this:
```
2018-10-24T17:58:33.825675444Z app[web.1]: [Wed Oct 24 17:58:33.825542 2018] [core:notice] [pid 68] AH00094: Command line: '/usr/sbin/apache2 -e info -D FOREGROUND'
```
And again, it seems to be working to start the parsoid service based on sshing into the docker container locally with `docker run -it <CONTAINER ID> /bin/bash` and checking the status with `service parsoid status`, and also by the output of the dokku logs. 

It's not working though, so I'm gonna get back to this later

**Comment by mattwr18** [comment]
Had a bit of a clean up in that I removed `VisualEditor` and added it as a submodule, which broke the site with an error saying
```
Fatal error: Uncaught ExtensionDependencyError: VisualEditor is not compatible with the current MediaWiki core (version 1.31.0), it requires: >= 1.32.0. in /var/www/html/includes/registration/ExtensionRegistry.php:278 Stack trace: #0 /var/www/html/includes/registration/ExtensionRegistry.php(158): ExtensionRegistry->readFromQueue(Array) #1 /var/www/html/includes/Setup.php(116): ExtensionRegistry->loadFromQueue() #2 /var/www/html/includes/WebStart.php(88): require_once('/var/www/html/i...') #3 /var/www/html/index.php(39): require('/var/www/html/i...') #4 {main} thrown in /var/www/html/includes/registration/ExtensionRegistry.php on line 278
```
Apparently, the master branch requires mediawiki v1.32, which is not available as an official mediawiki docker image, so I removed the submodule and followed the instructions to add branch `REL1_31` as a submodule, which brought the site back up, still without the ability to use VisualEditor, but it says that it is installed. 

I noticed that in our repo here, VisualEditor is the only of the submodules we have that cannot be clicked on to go to the parent repos, presumably because it's not tracking master?

**Comment by mattwr18** [comment]
Some notes from troubleshooting parsoid: 
This response looks normal
```
curl https://develop-official.hlpwiki.agileventures.org/api.php
```
Able to restart parsoid inside the docker container
```
service parsoid restart
[....] Restarting Parsoid HTTP service: parsoidStarted Parsoid server on port 8142
. ok 
```
Another command from the troubleshooting website, is getting connection refused on port 8142
```
curl -L https://develop-official.hlpwiki.agileventures.org:8142/localhost/v3/page/html/Main_Page
curl: (7) Failed to connect to develop-official.hlpwiki.agileventures.org port 8142: Connection refused
```
In verbose mode:
```
curl -vL https://develop-official.hlpwiki.agileventures.org:8142/localhost/v3/page/html/Main_Page
*   Trying 13.68.140.154...
* TCP_NODELAY set
* connect to 13.68.140.154 port 8142 failed: Connection refused
* Failed to connect to develop-official.hlpwiki.agileventures.org port 8142: Connection refused
* Closing connection 0
curl: (7) Failed to connect to develop-official.hlpwiki.agileventures.org port 8142: Connection refused
```
Over port 80, there is a response, although is saying page not found on server
```
curl -L http://develop-official.hlpwiki.agileventures.org:80/localhost/v3/page/html/Main_Page
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /localhost/v3/page/html/Main_Page was not found on this server.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at develop-official.hlpwiki.agileventures.org Port 80</address>
</body></html>
```
After setting up proxy mapping for `http:8142:80`, I was able to at least connect to it, but with the same response
```
curl -vL http://develop-official.hlpwiki.agileventures.org:8142/localhost/v3/page/html/Main_Page
*   Trying 13.68.140.154...
* Connected to develop-official.hlpwiki.agileventures.org (13.68.140.154) port 8142 (#0)
> GET /localhost/v3/page/html/Main_Page HTTP/1.1
> Host: develop-official.hlpwiki.agileventures.org:8142
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Sat, 27 Oct 2018 00:08:22 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 340
< Connection: keep-alive
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /localhost/v3/page/html/Main_Page was not found on this server.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at develop-official.hlpwiki.agileventures.org Port 8142</address>
</body></html>
* Connection #0 to host develop-official.hlpwiki.agileventures.org left intact
```
It's still not working. Although, now when I build it deploys the site to be available on port 8142 like so 
![screenshot at 2018-10-26 21 11 20](https://user-images.githubusercontent.com/26943915/47597273-c3840900-d963-11e8-9b78-e9e94321852f.png)
I guess this is what @tansaku was on about... setting up these proxy make them available externally and we just need them to be available internally for the parsoid service. 

Going through the documentation, it seems that having `settings.js` is not necessary with Parsoid greater than 0.60, so I removed it. Also setting `domain` and `prefix` are for older versions, so both were removed to no avail. 

Having a look here, http://dokku.viewdocs.io/dokku~v0.6.3/proxy/, it seems worth a try to port map from 8142 to 5000 and got this different error
```
curl -vL http://develop-official.hlpwiki.agileventures.org:8142/localhost/v3/page/html/Social_Prescribing_and_Self_Care_Wiki
*   Trying 13.68.140.154...
* Connected to develop-official.hlpwiki.agileventures.org (13.68.140.154) port 8142 (#0)
> GET /localhost/v3/page/html/Social_Prescribing_and_Self_Care_Wiki HTTP/1.1
> Host: develop-official.hlpwiki.agileventures.org:8142
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< Server: nginx
< Date: Sat, 27 Oct 2018 04:02:20 GMT
< Content-Type: text/html
< Content-Length: 641
< Connection: keep-alive
< ETag: "5b06dc58-281"
< 
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #6CABF7;
    color: #fff;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }
  div {
    position:absolute;
    top: 50%;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
  }
  p {
    color: #eee;
  }
  </style>
</head>

<body>
  <div>
    <h1>We're sorry, but something went wrong.</h1>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
* Connection #0 to host develop-official.hlpwiki.agileventures.org left intact
```
It would be nice to be able to check the parsoid.log, but since I can't, maybe it's time to call it a night

**Comment by tansaku** [comment]
great progress here @mattwr18 

would it make sense to set the proxy port map to include `http:8142:8142` ?

**Comment by mattwr18** [comment]
hey @tansaku I tried that as well, but then I noticed that in that dokku site above they were mapping it to port 5000, so I thought I'd give that a try as well.

**Comment by mattwr18** [comment]
Nice article that could potentially be helpful?
https://glebbahmutov.com/blog/running-multiple-applications-in-dokku/

**Comment by mattwr18** [comment]
Having pulled in the latest changes from master and armed with new tools to enter dokku container boxes, I pushed up the parsoid/visual editor branch and it looked like it wanted to load, and we are getting new errors now. 
![screenshot at 2018-11-08 16 11 53](https://user-images.githubusercontent.com/26943915/48221055-23bd7680-e378-11e8-8c7d-b72f4860aafc.png)
![screenshot at 2018-11-08 16 07 32](https://user-images.githubusercontent.com/26943915/48221089-3a63cd80-e378-11e8-9a0f-482cd4059ef2.png)

I looked at the logs and got this:
![screenshot at 2018-11-08 16 13 38](https://user-images.githubusercontent.com/26943915/48221196-94649300-e378-11e8-82e7-19765aa47742.png)

Searching the internet, I found a helpful comment from someone who goes by @tansaku 
https://www.mediawiki.org/w/index.php?title=Topic:Towxb6atgr4mhlcy&topic_showPostId=tpyvxwql9c3y0pyf#flow-post-tpyvxwql9c3y0pyf

**Comment by tansaku** [comment]
great progress here @mattwr18

**Comment by mattwr18** [comment]
New error when trying to edit with visual editor
![screenshot at 2018-11-12 09 56 42](https://user-images.githubusercontent.com/26943915/48347013-1cda8080-e664-11e8-8b00-bf21e98b15ea.png)

**Comment by mattwr18** [comment]
Have found this about the above issue
![screenshot at 2018-11-12 09 56 42](https://user-images.githubusercontent.com/26943915/48347775-6cba4700-e666-11e8-90a3-9325289fe56d.png)

**Comment by mattwr18** [comment]
changing the config in CustomSettings.php back to port 8142 and fixing the proxy port mappings to https:8142:8142, everything is suddenly working...

big ups to @mtc2013
